### ISSUE TITLE
Backend: Location Opening times editor metabox (no specific opening times)

### ISSUE THREAD

**Issue by anewholm** [wielebenwir/commons-booking-2#159] opened 2019-03-28 14:06 UTC
## Overview of the booking modes 

<img width="1400" alt="Bildschirmfoto 2019-05-23 um 12 16 32" src="https://user-images.githubusercontent.com/4009931/58246140-97dccc00-7d56-11e9-9437-1b7295781d4d.png">

- [ ] implement switch between "Always" (default) and "custom"
- [ ] implement 1-week opening hours metabox and link to advanced editor
- [ ] add metabox location contact 
- [ ] add location contact textarea_small to booking emails 

related: 

![openinghours-always-avalblable](https://user-images.githubusercontent.com/4009931/58245577-657e9f00-7d55-11e9-91fd-1613e419f406.png)
![openinghours](https://user-images.githubusercontent.com/4009931/58245578-66173580-7d55-11e9-930c-ed79431f2ce8.png)

**Comment by anewholm** [comment] 2019-03-28 14:08
why is this?
the vast majority of Places are not always open.
Do you mean that if there are _no_ open hours defined, that they do not restrict?

**Comment by anewholm** [comment] 2019-03-28 14:13
At the moment, the system creates default opening hours based on the default settings for day_start and day_end without the user needing to do anything. This is probably better as it will mean that all the other functions work properly. e.g. opening times widget.

Also, because there are opening times, by default the system will auto-link _all_ created items to the single opening times. This linking is a very good default behaviour I think.

**Comment by flegfleg** [comment] 2019-03-28 16:13
> @anewholm anewholm added the needs discussion  label 2 hours ago

Yes 👍

**Comment by flegfleg** [comment] 2019-03-28 16:18
> At the moment, the system creates default opening hours based on the default settings for day_start and day_end without the user needing to do anything. 

i would be worried that people will try to find where this (day_start & end) is defined. _Always open_ is not as convenient, but clearer in the end i think. 

> This is probably better as it will mean that all the other functions work properly. e.g. opening times widget.

what's the widget? the wizard? it should work with 00:00-23:59 too, right?

**Comment by flegfleg** [comment] 2019-04-17 10:14
* Set times 
* No specific opening times (people need to contact location after booking)

**Comment by flegfleg** [comment] 2019-05-07 22:57
duplicate of #69

**Closed** 2020-01-05 15:14 UTC
Labels: core, feature
