### ISSUE TITLE
Save page fails when using [cb2_bookings] shortcode

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#528] opened 2020-01-29 17:14 UTC
Page will not save when `[cb2_bookings]` shortcode is embedded: 

> Updating failed. Error message: The response is not a valid JSON response.

<img width="1089" alt="Bildschirmfoto 2020-01-29 um 18 11 52" src="https://user-images.githubusercontent.com/4009931/73379799-3694d180-42c3-11ea-82f0-efd74fade8ed.png">

Workaround: Install *Classic editor* plugin.

**Comment by anewholm** [comment] 2020-01-30 13:38
Cannot repeat this.
![image](https://user-images.githubusercontent.com/708045/73454351-3271be00-436e-11ea-917f-523cb8d63a4d.png)

**Comment by farbschein** [comment] 2020-01-30 13:49
@anewholm Can you tell on what wordpress-version you tried it and do you use Gutenberg-editor?

**Comment by farbschein** [comment] 2020-01-30 13:50
We got the issue on version 5.3.2

**Comment by anewholm** [comment] 2020-01-30 13:55
I am running Wordpress 5.3.2 and I sent the screenshot which shows I am using the new WordPress editor. Is that correct?

**Comment by anewholm** [comment] 2020-01-30 13:56
![image](https://user-images.githubusercontent.com/708045/73455613-b75dd700-4370-11ea-9949-6644c0205810.png)

**Comment by farbschein** [comment] 2020-01-30 13:57
Thank you. I also tried it on a fresh installation and couldn't reproduce the error. So I will close the issues. It was a single bug on the development system.

**Closed** 2020-01-30 13:58 UTC
Labels: bug
