### ISSUE TITLE
Booking on same day triggers an error

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commons-booking-2#520] opened 2020-01-28 21:04 UTC
Booking of a slot that has already started throws an error:
Member CB2_Item->do_action_[book](54)

WordPress database error: [datetime_from cannot be more than datetime_part_period_start]
INSERT INTO `wp_cb2_periods` (`author_ID`, `datetime_from`, `datetime_part_period_end`, `datetime_part_period_start`, `datetime_to`, `description`, `name`, `recurrence_type`) VALUES (1, '2020-01-24 19:54:08', '2020-01-24 21:00:00', '2020-01-24 09:00:00', NULL, '', 'Booking', NULL)
wp_cb2_periods

Desired behavoiur:
Bookings should be allowed until the end of the slot time.

**Comment by anewholm** [comment] 2020-02-03 12:23
This is not a bug. It was designed to do this. The error is custom and created by the Database. Same-day booking and indeed the buffer period for bookings is a design question as requests have come in from clients to prevent bookings for a given period. This is design and programming work that needs to be completed, not a bug.  

Also, it can be solved easily and is very healthy for the programmer to simply change the logic behind which date is used for the datetime_from field when creating bookings.

**Comment by anewholm** [comment] 2020-02-03 14:24
I will assign it to the startdate of the period being booked for now...

**Closed** 2020-02-03 14:56 UTC
Labels: needs discussion

**Comment by anewholm** [comment] 2020-02-03 15:03
Search for `CB2_Period::factory` in the `CB2_PeriodEntity` class to see where bookings are created :)
